### PR TITLE
Fixes file descriptor leak in certain use cases

### LINKED ISSUE #788: log4js version 2.10.0 is giving error when shutdown and process Exit called
**code:**
log4js.shutdown(() => { process.exit(1); });

**Error:**
log4js.fileAppender - Writing to file ../logs/ABC.log, error happened Error: write after end
at writeAfterEnd (/node_modules/readable-stream/lib/_stream_writable.js:288:12)
at RollingFileStream.Writable.write (/node_modules/readable-stream/lib/_stream_writable.js:332:20)
at Function.app.shutdown (node_modules/log4js/lib/appenders/file.js:69:12)
at appenders.filter.forEach.a (/node_modules/log4js/lib/log4js.js:273:52)
at Array.forEach (native)
at Object.shutdown (/node_modules/log4js/lib/log4js.js:273:37)
at process.exitHandler (XYZ.js:130:12)
at emitOne (events.js:96:13)
at process.emit (events.js:188:7)
at process.exit (internal/process.js:146:15)

### LINKED ISSUE #978: pattern for reloading log4js config when config file changes
I'm sure that a github issue is not the appropriate place for this, so I apologize, but I can't find any other place to ask the question.

I know that reloading on config file changes has been removed from log4js, but I am trying to do it myself and I am struggling to figure out how to do this without getting errors. Also, searching github repos for log4js and chokidar or watchr gives no results which makes me think this is not something many people are trying to do?

Is there a sample somewhere that could be added to the documentation to show how to do this? I am trying to use chokidar to do this but no matter what I try I end up with errors due to write operations occurring after the shutdown occurs.

### LINKED ISSUE #1005: log4js.shutdown() not working properly - Error [ERR_STREAM_WRITE_AFTER_END]: write after end
This was first brought up here https://github.com/log4js-node/log4js-node/issues/788, and I've upgraded to the latest version and the problem still persists.

log4js does not properly write to the file, it seems to close the stream flushing out the latest input, as seen by `log4js.fileAppender - Writing to file /home/userA/code/projectA/log/projectA-server-config.log, error happened  Error [ERR_STREAM_WRITE_AFTER_END]: write after end`.

**Code**

```javascript
function handleSignals() {
  // Handle e.g. ctrl+c and other graceful signals to exit
  ['SIGINT', 'SIGTERM'].forEach((signal) =>
    process.on(signal, (code) => {
      logger.info(
        `Exiting with code: ${code}. Gracefully cleaning up, please wait...`
      );
      shutdown(code);
    })
  );
}

function shutdown(exitCode) {
  process.exitCode = exitCode;
  // Make sure all logs have been written to files, stdout etc.
  log4js.shutdown(() => {
    console.log('### this is printed');
    // This should be removed when we handle graceful shutdown of all services
    process.exit(exitCode);
  });
}
```

**Output**

```sh
[2020-05-05T10:20:13.893+0200] [INFO] server - Exiting with code: SIGINT. Gracefully cleaning up, please wait...
log4js.fileAppender - Writing to file /home/userA/code/projectA/log/projectA-server.log, error happened  Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:257:14)
    at RollingFileStream.Writable.write (_stream_writable.js:306:5)
    at RollingFileStream.Writable.end (_stream_writable.js:617:10)
    at Function.app.shutdown (/home/userA/code/projectA/server/node_modules/log4js/lib/appenders/file.js:72:12)
    at /home/userA/code/projectA/server/node_modules/log4js/lib/log4js.js:117:59
    at Array.forEach (<anonymous>)
    at Object.shutdown (/home/userA/code/projectA/server/node_modules/log4js/lib/log4js.js:117:44)
    at shutdown (/home/userA/code/projectA/server/shutdown.js:18:10)
    at process.<anonymous> (/home/userA/code/projectA/server/signals.js:17:7)
    at process.emit (events.js:223:5) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}
log4js.fileAppender - Writing to file /home/userA/code/projectA/log/projectA-server-config.log, error happened  Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:257:14)
    at RollingFileStream.Writable.write (_stream_writable.js:306:5)
    at RollingFileStream.Writable.end (_stream_writable.js:617:10)
    at Function.app.shutdown (/home/userA/code/projectA/server/node_modules/log4js/lib/appenders/file.js:72:12)
    at /home/userA/code/projectA/server/node_modules/log4js/lib/log4js.js:117:59
    at Array.forEach (<anonymous>)
    at Object.shutdown (/home/userA/code/projectA/server/node_modules/log4js/lib/log4js.js:117:44)
    at shutdown (/home/userA/code/projectA/server/shutdown.js:18:10)
    at process.<anonymous> (/home/userA/code/projectA/server/signals.js:17:7)
    at process.emit (events.js:223:5) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}
log4js.fileAppender - Writing to file /home/userA/code/projectA/security/projectA-server-audit.log, error happened  Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:257:14)
    at RollingFileStream.Writable.write (_stream_writable.js:306:5)
    at RollingFileStream.Writable.end (_stream_writable.js:617:10)
    at Function.app.shutdown (/home/userA/code/projectA/server/node_modules/log4js/lib/appenders/file.js:72:12)
    at /home/userA/code/projectA/server/node_modules/log4js/lib/log4js.js:117:59
    at Array.forEach (<anonymous>)
    at Object.shutdown (/home/userA/code/projectA/server/node_modules/log4js/lib/log4js.js:117:44)
    at shutdown (/home/userA/code/projectA/server/shutdown.js:18:10)
    at process.<anonymous> (/home/userA/code/projectA/server/signals.js:17:7)
    at process.emit (events.js:223:5) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}
log4js.fileAppender - Writing to file /home/userA/code/projectA/log/projectA-server.log, error happened  Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:257:14)
    at RollingFileStream.Writable.write (_stream_writable.js:306:5)
    at RollingFileStream.Writable.end (_stream_writable.js:617:10)
    at Function.app.shutdown (/home/userA/code/projectA/server/node_modules/log4js/lib/appenders/file.js:72:12)
    at /home/userA/code/projectA/server/node_modules/log4js/lib/log4js.js:117:59
    at Array.forEach (<anonymous>)
    at Object.shutdown (/home/userA/code/projectA/server/node_modules/log4js/lib/log4js.js:117:44)
    at shutdown (/home/userA/code/projectA/server/shutdown.js:18:10)
    at process.<anonymous> (/home/userA/code/projectA/server/signals.js:17:7)
    at process.emit (events.js:223:5) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}
log4js.fileAppender - Writing to file /home/userA/code/projectA/log/projectA-server-config.log, error happened  Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:257:14)
    at RollingFileStream.Writable.write (_stream_writable.js:306:5)
    at RollingFileStream.Writable.end (_stream_writable.js:617:10)
    at Function.app.shutdown (/home/userA/code/projectA/server/node_modules/log4js/lib/appenders/file.js:72:12)
    at /home/userA/code/projectA/server/node_modules/log4js/lib/log4js.js:117:59
    at Array.forEach (<anonymous>)
    at Object.shutdown (/home/userA/code/projectA/server/node_modules/log4js/lib/log4js.js:117:44)
    at shutdown (/home/userA/code/projectA/server/shutdown.js:18:10)
    at process.<anonymous> (/home/userA/code/projectA/server/signals.js:17:7)
    at process.emit (events.js:223:5) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}
log4js.fileAppender - Writing to file /home/userA/code/projectA/security/projectA-server-audit.log, error happened  Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:257:14)
    at RollingFileStream.Writable.write (_stream_writable.js:306:5)
    at RollingFileStream.Writable.end (_stream_writable.js:617:10)
    at Function.app.shutdown (/home/userA/code/projectA/server/node_modules/log4js/lib/appenders/file.js:72:12)
    at /home/userA/code/projectA/server/node_modules/log4js/lib/log4js.js:117:59
    at Array.forEach (<anonymous>)
    at Object.shutdown (/home/userA/code/projectA/server/node_modules/log4js/lib/log4js.js:117:44)
    at shutdown (/home/userA/code/projectA/server/shutdown.js:18:10)
    at process.<anonymous> (/home/userA/code/projectA/server/signals.js:17:7)
    at process.emit (events.js:223:5) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}
log4js.fileAppender - Writing to file /home/userA/code/projectA/log/projectA-server.log, error happened  Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:257:14)
    at RollingFileStream.Writable.write (_stream_writable.js:306:5)
    at RollingFileStream.Writable.end (_stream_writable.js:617:10)
    at Function.app.shutdown (/home/userA/code/projectA/server/node_modules/log4js/lib/appenders/file.js:72:12)
    at /home/userA/code/projectA/server/node_modules/log4js/lib/log4js.js:117:59
    at Array.forEach (<anonymous>)
    at Object.shutdown (/home/userA/code/projectA/server/node_modules/log4js/lib/log4js.js:117:44)
    at shutdown (/home/userA/code/projectA/server/shutdown.js:18:10)
    at process.<anonymous> (/home/userA/code/projectA/server/signals.js:17:7)
    at process.emit (events.js:223:5) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}
log4js.fileAppender - Writing to file /home/userA/code/projectA/log/projectA-server-config.log, error happened  Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:257:14)
    at RollingFileStream.Writable.write (_stream_writable.js:306:5)
    at RollingFileStream.Writable.end (_stream_writable.js:617:10)
    at Function.app.shutdown (/home/userA/code/projectA/server/node_modules/log4js/lib/appenders/file.js:72:12)
    at /home/userA/code/projectA/server/node_modules/log4js/lib/log4js.js:117:59
    at Array.forEach (<anonymous>)
    at Object.shutdown (/home/userA/code/projectA/server/node_modules/log4js/lib/log4js.js:117:44)
    at shutdown (/home/userA/code/projectA/server/shutdown.js:18:10)
    at process.<anonymous> (/home/userA/code/projectA/server/signals.js:17:7)
    at process.emit (events.js:223:5) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}
log4js.fileAppender - Writing to file /home/userA/code/projectA/security/projectA-server-audit.log, error happened  Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:257:14)
    at RollingFileStream.Writable.write (_stream_writable.js:306:5)
    at RollingFileStream.Writable.end (_stream_writable.js:617:10)
    at Function.app.shutdown (/home/userA/code/projectA/server/node_modules/log4js/lib/appenders/file.js:72:12)
    at /home/userA/code/projectA/server/node_modules/log4js/lib/log4js.js:117:59
    at Array.forEach (<anonymous>)
    at Object.shutdown (/home/userA/code/projectA/server/node_modules/log4js/lib/log4js.js:117:44)
    at shutdown (/home/userA/code/projectA/server/shutdown.js:18:10)
    at process.<anonymous> (/home/userA/code/projectA/server/signals.js:17:7)
    at process.emit (events.js:223:5) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}
### this is printed
npm run start:server exited with code SIGINT
```

### LINKED ISSUE #1058: Memory not release after shutdown
log4js version: 6.3.0

```
const {configure, getLogger, shutdown} = require('log4js');

configure({
  appenders: {
    everything: { type: 'file', filename: 'all-the-logs.log' }
  },
  categories: {
    default: { appenders: [ 'everything' ], level: 'debug' }
  }
});

const logger = getLogger();

let s = [];
for (let i = 0; i < 100; i++) {
  s.push("xxxx");
}
let s1 = s.join(",");

setTimeout(()=>{
  console.log("after setTimeout", process.memoryUsage().rss / Math.pow(1024, 2));
}, 10000)

for (let j = 0; j < 10; j++) {
  for (let i = 0; i < 10000; i++) {
    logger.debug(s1 + i);
  }
  console.log(process.memoryUsage().rss / Math.pow(1024, 2));
}
console.log("before shutdown", process.memoryUsage().rss / Math.pow(1024, 2));
shutdown(()=>{
  console.log("after shutdown", process.memoryUsage().rss / Math.pow(1024, 2));
})

```

output:

```
41.60546875
53.203125
64.42578125
71.15234375
86.609375
102.85546875
110.1640625
117.4140625
124.35546875
131.5390625
before shutdown 131.5390625
after shutdown 134.94921875
after setTimeout 134.96875
```

### PR DESCRIPTION
**Pull request by peteriman**
Fixes #788, Fixes #978, Fixes #1005, Fixes #1058
Additionally, this PR supersedes PR #1083

**Allow multiple configure() calls:**
Calling multiple `configure()` without `shutdown()` may leave resources open (file handles, network connections, etc).
This patch explicitly does a `shutdown() `for subsequently `configure()` to prevent resource leaks.

**Allow multiple shutdown() calls:**
Within the `shutdown()`, it now clears `appenders` and `categories`. Repeated/duplicated `shutdown()` calls will no longer traverse the same `appenders` to shut them down them again which will result in `Error [ERR_STREAM_WRITE_AFTER_END]: write after end`.

### CODE REVIEW

**Comment by thernstig** [comment]
@peteriman you marked https://github.com/log4js-node/log4js-node/issues/1005 as fixed by this, but are you sure that is the case? I saw your comment in the thread, but have not had time to verify it.

**Comment by peteriman** [comment]
@thernstig I'm quite sure there were multiple concurrent `log4js.shutdown()` calls based on your logs in #1005.

Nevertheless, please take some time to verify my comments in #1005. 
If possible, I will be grateful if you could apply the changes in this PR to be an extra pair of eyes to verify the fix. 

### Read onwards for the rationale of this fix:

The issue is due to `log4js.shutdown()` doesn't reset the current `appenders`.
It does a clone to `appendersToCheck` for appenders traversal to close the resources but does not clear `appenders`.
https://github.com/log4js-node/log4js-node/blob/52185a498408513dd813d6daed83329edca63b3d/lib/log4js.js#L90-L95

`log4js.shutdown()` will call the `app.shutdown()` of the fileAppenders which writes `''` before closing the file.
https://github.com/log4js-node/log4js-node/blob/52185a498408513dd813d6daed83329edca63b3d/lib/appenders/file.js#L78-L81

On the second `log4js.shutdown()`, as traverses the same `appenders`, the error will occur as it attempts to write to an already closed file, resulting in `Error [ERR_STREAM_WRITE_AFTER_END]: write after end`.

The fix resets the appenders, releasing the resources. 
That prevents subsequent `log4js.shutdown()` calls from re-visiting them again.

```diff
   // Clone out to maintain a reference
   const appendersToCheck = Array.from(appenders.values());

+  // Reset immediately to prevent leaks
+  appenders.init();
+  categories.init();

   // Call each of the shutdown functions in parallel
   const shutdownFunctions = appendersToCheck.reduceRight(
     (accum, next) => (next.shutdown ? accum + 1 : accum),
     0
   );
```

File: lib/log4js.js [hunk 1]
```diff
@@ -87,15 +92,25 @@ function shutdown(cb) {
   // not being able to be drained because of run-away log writes.
   enabled = false;
 
-  // Call each of the shutdown functions in parallel
+  // Clone out to maintain a reference
   const appendersToCheck = Array.from(appenders.values());
+
+  // Reset immediately to prevent leaks
+  appenders.init();
+  categories.init();
```
Comment (thernstig) [inline lib/log4js.js:100]: Is `categories.init();` even necessary, considering that `appenders.init();` sets up categories as well? No matter I still think it makes sense to call both here anyway.

Comment (thernstig) [reply lib/log4js.js:100]: Also I never cloned the entire repo to check this logic here, but this means an stdout appender is added immediately back. Just making sure that cannot cause any trouble?

Comment (peteriman) [reply lib/log4js.js:100]: > Is `categories.init();` even necessary, considering that `appenders.init();` sets up categories as well? No matter I still think it makes sense to call both here anyway.

I thought so too. But apparently, `appenders` and `categories` are separate. 
Both have their own cache and add their own listeners to the `configuration` object.

So there is a need to clear both to reset tot the same factory default state when you first `require(log4js)`.

## appenders
https://github.com/log4js-node/log4js-node/blob/0aed197dd36868d0a83e43f44bd9439dc85fda54/lib/appenders/index.js#L21

https://github.com/log4js-node/log4js-node/blob/0aed197dd36868d0a83e43f44bd9439dc85fda54/lib/appenders/index.js#L129

## categories
https://github.com/log4js-node/log4js-node/blob/0aed197dd36868d0a83e43f44bd9439dc85fda54/lib/categories.js#L6

https://github.com/log4js-node/log4js-node/blob/0aed197dd36868d0a83e43f44bd9439dc85fda54/lib/categories.js#L165

## configuration
https://github.com/log4js-node/log4js-node/blob/0aed197dd36868d0a83e43f44bd9439dc85fda54/lib/configuration.js#L17-L20
https://github.com/log4js-node/log4js-node/blob/0aed197dd36868d0a83e43f44bd9439dc85fda54/lib/configuration.js#L37-L48

**Comment by thernstig** [comment]
I think it looks good, not sure if @nomiddlename wants to LGTM this or not.

File: lib/log4js.js (hunk 1 above)
Comment (peteriman) [reply lib/log4js.js:100]: > Also I never cloned the entire repo to check this logic here, but this means an stdout appender is added immediately back. Just making sure that cannot cause any trouble?

Yup, I've checked. In fact, this is the same factory default behavior when you first `require('log4js')`.

https://github.com/log4js-node/log4js-node/blob/0aed197dd36868d0a83e43f44bd9439dc85fda54/lib/appenders/index.js#L105

So what I did was to wrap around it so that I can call `appenders.init()` in `log4js.shutdown()`.
Hence, calling `log4js.shutdown()` will now reset back to same factory default state when you first `require('log4js')`.

```diff
- setup({ appenders: { out: { type: 'stdout' } }, categories: { default: { appenders: ['out'], level: 'trace' } } });
+ const init = () => {
+   setup({ appenders: { out: { type: 'stdout' } }, categories: { default: { appenders: ['out'], level: 'trace' } } });
+ };
+ init();
...
+ module.exports.init = init;
```

**Comment by peteriman** [comment]
@thernstig I'm thinking of adding a few more automated test cases and after that, I can merge it in. :grin:

**Comment by peteriman** [comment]
@thernstig Your questions were of great help. I should add a few more automated test cases to cover those.
After that, I can merge it in. 😁

**Comment by peteriman** [comment]
Released in `log4js@6.4.0`.
